### ISSUE TITLE
[blockqueue]  Error processing block #1385071 (b80755 <~ a37b08) Txs:1, Unc: 0: 

### ISSUE THREAD

**Issue by abaoj** [adridadou/eth-contract-api#13]
-------------------
eth-contract-api\src\test\java\org\adridadou\TestnetConnectionTest.java
@Test
    public void run() throws Exception {
        run(testnet, "cow", "");
    }

-------log---------

18:10:08.337 INFO [sync]  Peer 8246787f: header sync completed, [2] headers in queue
18:10:09.135 INFO [blockqueue]  No parent on the chain for block.number: 1385072 block.hash: 8e5ba0
18:10:14.172 ERROR [blockqueue]  Error processing block #1385071 (b80755 <~ a37b08) Txs:1, Unc: 0: 
java.lang.NullPointerException
	at org.ethereum.trie.TrieImpl.delete(TrieImpl.java:286)
	at org.ethereum.trie.TrieImpl.insertOrDelete(TrieImpl.java:203)
	at org.ethereum.trie.TrieImpl.update(TrieImpl.java:133)
	at org.ethereum.trie.SecureTrie.update(SecureTrie.java:25)
	at org.ethereum.trie.SecureTrie.delete(SecureTrie.java:30)
	at org.ethereum.db.ContractDetailsImpl.put(ContractDetailsImpl.java:60)
	at org.ethereum.db.ContractDetailsCacheImpl.commit(ContractDetailsCacheImpl.java:163)
	at org.ethereum.db.RepositoryTrack.commit(RepositoryTrack.java:308)
	at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:744)

**Comment by adridadou** [comment]
Hi,
it seems that there is an issue with EthereumJ. I've got this issue once.

Are you using develop branch or one of the release? 

I will try to update the version maybe it will help. In the meantime try deleting the db and sync again

**Comment by abaoj** [comment]
using develop branch， I have already I have already deleted  the db， it`s ok, thanks

**Comment by abaoj** [comment]
What is different  Between testnet And morden  ？
eth-contract-api\src\test\java\org\adridadou\TestnetConnectionTest.java
private final TestnetEthereumFacadeProvider testnet = new TestnetEthereumFacadeProvider();
private final MordenEthereumFacadeProvider morden = new MordenEthereumFacadeProvider();
private final MainEthereumFacadeProvider main = new MainEthereumFacadeProvider();

**Comment by adridadou** [comment]
Testnest is ether.camp testnet 
Morden is the public testnet
