### ISSUE TITLE
java.io.FileNotFoundException: C:\Users\pc\Library\Ethereum\keystore\cow (系统找不到指定的路径。)

### ISSUE THREAD

**Issue by abaoj** [adridadou/eth-contract-api#14]
java.io.FileNotFoundException: C:\Users\pc\Library\Ethereum\keystore\cow (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:504)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1817)
	at org.adridadou.ethereum.keystore.Keystore.fromKeystore(Keystore.java:31)
	at org.adridadou.ethereum.provider.MainEthereumFacadeProvider.getKey(MainEthereumFacadeProvider.java:30)
	at org.adridadou.TestnetConnectionTest.run(TestnetConnectionTest.java:36)
	at org.adridadou.TestnetConnectionTest.run(TestnetConnectionTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by abaoj** [comment]
Solved, thank you

**Comment by adridadou** [comment]
Ok perfect!
If anyone has the same issue, the Morden facade takes the id you give it and look for the keystore json file in the testnet folder.

Here you have no "cow" file obviously.
