### ISSUE TITLE
how to run TestnetConnectionTest.java

### ISSUE THREAD

**Issue by cheershendtco** [adridadou/eth-contract-api#28]
Hi
I use mvn compile eth-contract-api-develop
I got this result.

```
cheer@cheer-H97-D3H:~/mtest/eth-contract-api-develop$ mvn compile
```

```
[INFO] argLine set to -javaagent:/home/cheer/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/cheer/mtest/eth-contract-api-develop/target/jacoco.exec,excludes=**/*Test.*:**/*Exception.*:**/SolidityContractImpl.*
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ eth-contract-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cheer/mtest/eth-contract-api-develop/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ eth-contract-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 59 source files to /home/cheer/mtest/eth-contract-api-develop/target/classes
[INFO] /home/cheer/mtest/eth-contract-api-develop/src/main/java/org/adridadou/ethereum/EthereumFacade.java: Some input files use unchecked or unsafe operations.
[INFO] /home/cheer/mtest/eth-contract-api-develop/src/main/java/org/adridadou/ethereum/EthereumFacade.java: Recompile with -Xlint:unchecked for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:27 min
[INFO] Finished at: 2016-10-06T17:33:04+08:00
[INFO] Final Memory: 25M/233M
[INFO] ------------------------------------------------------------------------


```

what can I do next?
how to run TestnetConnectionTest.java
Thanks !

I try this 
`mvn exec:java -Dexec.mainClass=org.adridadou.TestnetConnectionTest`

but I got
```

[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ eth-contract-api ---
[WARNING] 
java.lang.ClassNotFoundException: org.adridadou.TestnetConnectionTest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:44 min
[INFO] Finished at: 2016-10-06T17:47:45+08:00
[INFO] Final Memory: 17M/167M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project eth-contract-api: An exception occured while executing the Java class. org.adridadou.TestnetConnectionTest -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

**Comment by adridadou** [comment]
What you did only compiles the application. You said you are using Eclipse right? 
First, you need to open the project in Eclipse as a maven project. Then you should be able to run TestnetConnectionTest by right clicking on it and chose the option "run the test ... " or something like that.

**Comment by adridadou** [comment]
For more information, please have a look at "how to use maven in Eclipse" and "how to run a JUnit test in Eclipse"

**Comment by cheershendtco** [comment]
I use `mvn test`
and I got
```

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.adridadou.util.KeystoreTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.349 sec - in org.adridadou.util.KeystoreTest
Running org.adridadou.ethereum.EthereumFacadeTest
15:02:01.727 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
15:02:01.727 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
15:02:01.728 INFO [general]  Config ( no  ): user properties from resource 'user.conf'
15:02:01.728 INFO [general]  Config ( no  ): user properties from file '/home/cheer/mtest/eth-contract2/config/ethereumj.conf'
15:02:01.728 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
15:02:01.729 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
15:02:01.729 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
15:02:01.729 INFO [general]  Config ( no  ): config passed via constructor
15:02:01.831 INFO [general]  New nodeID generated: fa368bee88e4630cd6e8014ddfa2f04667796cae91bda5d91f534e6cb4ab1e40bd9b971fbb456bd10462217ab35d59bdda47a466a1cf8c77ab05ee002538632b
15:02:01.831 INFO [general]  Generated nodeID and its private key stored in database/nodeId.properties
15:02:02.636 INFO [mine]  Calculating light dataset...
15:02:04.358 INFO [mine]  Light dataset calculated.
15:02:04.359 INFO [mine]  Writing light dataset to /home/cheer/mtest/eth-contract2/database/mine-dag-light.dat
*** calling contract myMethod
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.033 sec - in org.adridadou.ethereum.EthereumFacadeTest
Running org.adridadou.TestnetConnectionTest
*** calling contract myMethod
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.43 sec - in org.adridadou.TestnetConnectionTest
Running org.adridadou.EthereumProviderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.417 sec - in org.adridadou.EthereumProviderTest

Results :

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0


```

Thanks.

**Comment by adridadou** [comment]
Sorry but I still don't get what you are trying to do. Please contact me on gitter so we can discuss this. 
A reminder, eth-contract-api is not an application, it's a library. So it doesn't make much sense to simply "run" it. There is a test to see how to use it but that's pretty much it. But contact me on gitter, if possible share with me the project you are working on (publish it on github if possible) and I'll gladly help you
